

# This is a basic workflow to help you get started with Actions

 

name: Azure Storage Account Deploy

 

# Controls when the workflow will run

on:

  # Triggers the workflow on push or pull request events but only for the "main" branch

  push:

    branches: [ "main" ]

  pull_request:

    branches: [ "main" ]

 

  # Allows you to run this workflow manually from the Actions tab

  workflow_dispatch:

 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:


  # This workflow contains a single job called "Lint"

  Lint:

    name: runBicepLinter

    # The type of runner that the job will run on

    runs-on: ubuntu-latest

 

    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - uses: actions/checkout@v3

 

      - name: Create Output Directory

        run: |

          mkdir -p ${{ github.workspace }}/src/bicep/jsonFilesForScan

 

      - name: Azure-Login

        uses: azure/login@v1

        with:

          creds: ${{ secrets.AZURE_CREDENTIALS }}

 

      - name: Run Bicep Linter

        working-directory: '${{github.workspace}}/Source/Bicep'

        run: |

          # az bicep build --file ./azure_resource.bicep  --outdir ${{ env.TEMPLATE_FILE_DIRECTORY }}/jsonFilesForScan

          # ls ${{ env.TEMPLATE_FILE_DIRECTORY }}/jsonFilesForScan

          az bicep build --file ./namespace.bicep  --outdir ./jsonFilesForScan

          ls ./jsonFilesForScan

 

 

  # This workflow contains a single job called "Validate"

  Validate:

    name: runTemplateValidation

    # The type of runner that the job will run on

    runs-on: ubuntu-latest

    needs: [Lint]

 

    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - uses: actions/checkout@v3

 

      - name: Azure-Login

        uses: azure/login@v1

        with:

          creds: ${{ secrets.AZURE_CREDENTIALS }}

 

      - name: Run Template Validation

        working-directory: '${{github.workspace}}/Source/Bicep'

        run: |

          az deployment group validate --name mydeployment1 --resource-group vibgok  --template-file ./azure_resource.bicep --parameters ./parameter.json



  # This workflow contains a single job called "Preview"

  Preview:

    name: runWhatIfTests

    # The type of runner that the job will run on

    runs-on: ubuntu-latest

    needs: [Validate]

 

    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - uses: actions/checkout@v3

 

      - name: Azure-Login

        uses: azure/login@v1

        with:

          creds: ${{ secrets.AZURE_CREDENTIALS }}

 

      - name: Run What-If Tests

        working-directory: '${{github.workspace}}/Source/Bicep'

        run: |

          az deployment group what-if --name mydeployment1 --resource-group vibgok --template-file ./azure_resource.bicep --parameters ./parameter.json

 

 

  # This workflow contains a single job called "Deploy"

  Deploy:

    name: runDeployment

    # The type of runner that the job will run on

    runs-on: ubuntu-latest

    needs: [Preview]

 

    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - uses: actions/checkout@v3

 

      - name: Azure-Login

        uses: azure/login@v1

        with:

          creds: ${{ secrets.AZURE_CREDENTIALS }}

 

      - name: Deploy Resource

        working-directory: '${{github.workspace}}/Source/Bicep'

        run: |

          az deployment group create --resource-group vibgok --template-file ./azure_resource.bicep --parameters ./parameter.json
